server:
  port: 9000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: RESTAURANT-SERVICE
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurants/**
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
        - id: FOOD-SERVICE
          uri: lb://FOOD-SERVICE
          predicates:
            - Path=/food/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost